widgets:
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Junzhuo Zhou
        # Author title
        author_title: HaoYu lab, SUSTech
        # Author's current location
        location: 
        # URL or path to the avatar image
        avatar: /img/me.png
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar:
        # URL or path for the follow button
        follow_link: 'https://github.com/zao111222333'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Email:
                icon: fa fa-envelope
                url: 'mailto:zhou@junzhuo.me'
            Google-Scholar:
                icon: fa fa-graduation-cap
                url: 'https://scholar.google.com/citations?hl=en&user=Rae-5RYAAAAJ'
            Github:
                icon: fab fa-github
                url: 'https://github.com/zao111222333'
            
    -
        type: toc
        position: left
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 6