#! /bin/zsh
hexo clean
mv source/_posts/About.md source/_posts/About.md.bak
mv source/_posts/MyCV.md source/_posts/MyCV.md.bak
hexo g
mv public public_root
rm -rf public_root/Categories
rm -rf public_root/tags
mv source/_posts source/_posts_bak
# for News
Bulid_Archive(){
    Dir=$1
    mkdir source/_posts
    cp -r source/_posts_bak/$Dir source/_posts/$Dir
    hexo g
    mv public/categories public/Categories
    mv public/Tags public/Tags
    mv public/Archive/index.html public_root/$Dir/index.html
    # Mac
    sed -i "" "s/Archives -/${Dir} -/g" public_root/$Dir/index.html
    # Linux
    # sed -i "s/Archives/${Dir}/g" public_root/$Dir/index.html
    cp -r public/Archive/* public_root/$Dir/
    mv public/Categories public_root/$Dir/Categories
    mv public/Tags public_root/$Dir/Tags
    for file in $(find public_root/$Dir -name '*html') then;
    do 
    echo $file
    sed -i "" "s/href=\"\/Categories/href=\"\/${Dir}\/Categories/g" $file
    sed -i "" "s/href=\"\/Tags/href=\"\/${Dir}\/Tags/g" $file
    done
    rm -rf public
    rm -rf source/_posts
}
Bulid_Categories(){
    Dir=$1
    mkdir source/_posts
    cp -r source/_posts_bak/$Dir source/_posts/$Dir
    hexo g
    mv public/categories public/Categories
    mv public/Tags public/Tags
    mv public/index.html public_root/$Dir/index.html
    mv public/page public_root/$Dir/page
    # Mac
    sed -i "" "s/\<title\>Junzhuo\<\/title\>/\<title\>${Dir} - Junzhuo\<\/title\>/g" public_root/$Dir/index.html
    # Linux
    # sed -i "s/Categories/${Dir}/g" public_root/$Dir/index.html
    cp -r public/$Dir/* public_root/$Dir/
    mv public/Categories public_root/$Dir/Categories
    mv public/Tags public_root/$Dir/Tags
    for file in $(find public_root/$Dir -name '*html') then;
    do 
    echo $file
    sed -i "" "s/href=\"\/Categories/href=\"\/${Dir}\/Categories/g" $file
    sed -i "" "s/href=\"\/Tags/href=\"\/${Dir}\/Tags/g" $file
    done
    rm -rf public
    rm -rf source/_posts
}
Bulid_Archive News
Bulid_Archive Researches
Bulid_Archive Projects
Bulid_Archive Publications
Bulid_Categories Blogs

# HomePage & CV
mkdir source/_posts
cp -r source/_posts_bak/About.md.bak source/_posts/About.md
cp -r source/_posts_bak/MyCV.md.bak source/_posts/MyCV.md
hexo g
mv public/About/index.html public_root/index.html
mv public/MyCV public_root/MyCV
rm -rf public
rm -rf source/_posts
# CV
sed -i "" "s/<title>/<title>CV - /g" public_root/MyCV/index.html
sed -i "" "s/is-10/is-12/g" public_root/MyCV/index.html
mv public_root public


mv source/_posts_bak source/_posts
mv source/_posts/About.md.bak source/_posts/About.md
mv source/_posts/MyCV.md.bak source/_posts/MyCV.md
# rm -rf public/page
# mv public/tags
rm -rf public/Archive
for file in $(find public/ -name '*\ *') then;
do 
rm -rf $file" "*
done
for file in $(find public/News/Categories -name '*html') then;
do 
echo $file
sed -i "" "s/refresh\" content=\"0/refresh\" content=\"-1/g" $file
done

# Timeline
python3 fetch.py News
python3 fetch.py Researches
python3 fetch.py Projects
python3 fetch.py Publications
# Correct
python3 correct-is-active.py

# scp -r -i ~/.ssh/vps-HK ~/Desktop/junzhuo.me/public admin@47.243.126.173:/junzhuo.me/
node publish.js
